"""Add content_cluster and completed_at columns to Job model

Revision ID: 501dcbdcea08
Revises: b00f7d8c1714
Create Date: 2025-04-11 14:35:09.997385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501dcbdcea08'
down_revision = 'b00f7d8c1714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_cluster', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('content_cluster')

    # ### end Alembic commands ###
