"""Add article_ideas and final_plan columns to Job model

Revision ID: 8a236c82a99d
Revises: 501dcbdcea08
Create Date: 2025-04-12 11:36:48.931641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a236c82a99d'
down_revision = '501dcbdcea08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_ideas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('final_plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('final_plan')
        batch_op.drop_column('article_ideas')

    # ### end Alembic commands ###
