"""Add brand_brief and search_analysis columns to Job model

Revision ID: b00f7d8c1714
Revises: a84a08256e9b
Create Date: 2025-04-11 14:32:33.075680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b00f7d8c1714'
down_revision = 'a84a08256e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_content_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('search_results', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('search_results_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brand_brief', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('search_analysis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('search_analysis')
        batch_op.drop_column('brand_brief')
        batch_op.drop_column('search_results_count')
        batch_op.drop_column('search_results')
        batch_op.drop_column('website_content_length')

    # ### end Alembic commands ###
